language: c++
os: linux
sudo: false

matrix:
  include:
    # Clang 3.5, release / debug
    - env: COMPILER='clang++-3.5' BUILD_TYPE='Debug'
      addons: &clang35
        apt:
          sources:
            - llvm-toolchain-precise-3.5
            - ubuntu-toolchain-r-test
            - boost-latest
          packages:
            - clang-3.5
            - libboost1.55-all-dev

    - env: COMPILER='clang++-3.5' BUILD_TYPE='Release'
      addons: *clang35

    # Clang 3.6, release / debug
    - env: COMPILER='clang++-3.6' BUILD_TYPE='Debug'
      addons: &clang36
        apt:
          sources:
            - llvm-toolchain-precise-3.6
            - ubuntu-toolchain-r-test
            - boost-latest
          packages:
            - clang-3.6
            - libboost1.55-all-dev

    - env: COMPILER='clang++-3.6' BUILD_TYPE='Release'
      addons: *clang36

    # Clang 3.7, release / debug
    - env: COMPILER='clang++-3.7' BUILD_TYPE='Debug'
      addons: &clang37
        apt:
          sources:
            - llvm-toolchain-precise-3.7
            - ubuntu-toolchain-r-test
            - boost-latest
          packages:
            - clang-3.7
            - libboost1.55-all-dev

    - env: COMPILER='clang++-3.7' BUILD_TYPE='Release'
      addons: *clang37

    # GCC 4.8, release / debug
    - env: COMPILER='g++-4.8' BUILD_TYPE='Debug'
      addons: &gcc48
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - boost-latest
         packages:
            - g++-4.8
            - libboost1.55-all-dev

    - env: COMPILER='g++-4.8' BUILD_TYPE='Release'
      addons: *gcc48

    # GCC 4.9, release / debug
    - env: COMPILER='g++-4.9' BUILD_TYPE='Debug'
      addons: &gcc49
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - boost-latest
          packages:
            - g++-4.9
            - libboost1.55-all-dev

    - env: COMPILER='g++-4.9' BUILD_TYPE='Release'
      addons: *gcc49

    # GCC 5, release / debug
    - env: COMPILER='g++-5' BUILD_TYPE='Debug'
      addons: &gcc5
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - boost-latest
          packages:
            - g++-5
            - libboost1.55-all-dev

    - env: COMPILER='g++-5' BUILD_TYPE='Release'
      addons: *gcc5

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}

  - CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz"
  - mkdir cmake && travis_retry wget --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
  - export PATH=${DEPS_DIR}/cmake/bin:${PATH}

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build
  - cmake .. -DCMAKE_CXX_COMPILER=${COMPILER} -DCMAKE_BUILD_TYPE=${BUILD_TYPE}

script:
  - cmake --build .
  - ./Main
